### ISSUE TITLE
Address every TODO in code

### ISSUE THREAD

**Issue by fulldecent** [Genobank/genobankioj#3]
This issue relates to ALL repositories. See link below. I have no idea why this is in the Java project repo.

**Comment by fulldecent** [comment]
There are 19 items remaining and they are listed at

https://github.com/search?p=2&q=org%3AGenobank+todo&type=Code

**Comment by MoMannn** [comment]
Reduce commitment: only create issues for each todo and link to line in code.
@xpepermint

**Comment by xpepermint** [comment]
Done
